title: <p align="center"> Jatin Mulchandani </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://in.linkedin.com/in/jatin-mulchandani-125510125">LinkedIn</a> |
  <a href="https://github.com/jatin0751">GitHub</a>
  
  <br>   
  Analytics Professional with more than 4 years of work experience in executing data driven solutions. 
  Proficient knowledge in Data Science, Machine Learning, Statistics, Analytics and Data Visualization. 
  Keen skill in understanding business operations and leveraging analytical tools for impactful analysis of data.
  <br>
  </p>



theme: jekyll-theme-minimal
